# -*- coding: utf-8 -*-
"""AIML lab(1)(20221cit0078

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNgbGXgtw48s6sLRCfrR_7aYbC9gUK-W
"""

import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

print("hello my dear friends")

a=50
b=50
c=a+b
print(c)

x="hello"
x

l1=[1,2,3,4,5,6]

for x in l1:
  print(x)

l1.append(7)

l1

l2=[8,9,10]

l3=l1+l2
l3

l1=[1,1,1,2,2,2,3,3,3,4,4]
l2=[]
for x in l1:
  if x not in l2:
    l2.append(x)
l2

l2=list(set(l1))
l2

a=10
b=1.5
c='jamil'

print(type(a))
print(type(b))
print(type(c))

for x in range(6):
  print(x)

#slicing
l1=[1,2,3,4,5,6,7,8]
print(l1[:4])

l1=[1,2,3,4,5,6,7,8]
print(l1)

l1[-1]

#for reversing in one line

l1[::-1]

str1=input("Enter the name:")
str2=str1[::-1]

if str1==str2:
  print("The string is palindrome")
else:
  print("it is not a palindrome")

days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday"  in days

days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday"  not in days

list=["red","orange","pink","black"]
print(list)
list.clear()
print(list)

nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

A=[1,2,3,4,5]
B=[5,6,7,3,6]
print(A)
print(B)
A.extend(B)
print(A)

a=["a","b","c","d"]
print(a)
a.append("e")
print(a)

#Tuple

a=(5,)
print(a)
print(type(a))

a=(1,2,3,4,5)
print(a)

b=(6.5,5.9,2.0)
print(b)

#creating tuple with string

c=('one','two','three')
c

#tuple with multipal data type

mix=('hello',708,66.8,1,2)
mix

#accessing item of tuples

a=(1,2,3,4,'hello')
print(a[4])

#dictionary creating

a={
    'name':'joy',
    'age':23,
    'education':'engineer'
}
print(a)

len(a)

type(a)

x=a.keys()
x

y=a.values()
y

z=a.items()
z

#sets

set1={1,2,3,4}
print(set1)

3 #duplicates not allowed

set={1,2,3,4,5,6,7,1,1}
set

def add():
    a=2
    b=3
    sum=a+b
add()
print(add())